### ISSUE TITLE
Participarea la EGOI 2023

### ISSUE THREAD

**Issue by DanaLica** [asociatia-sepi/documente-publice#36]
EGOI 2023 a avut loc la Lund, Suedia.
Pagina de internet: https://egoi23.se/

Echipa României a fost alcătuită din:

Concurenți:

- Slănină Iulia - Medalie AUR
- Dumitrescu Karina-Andreea
- Șerban Teodora-Maria - Medalie BRONZ
- Duguleanu Ana-Valeria

Leaderi

- Livia Măgureanu
- Nicola Alexandra-Mihaela

Necesar un raport al deplasării și acte contabile pentru decontare

**Comment by mariusnicoli** [comment]
Postare pe pagina SEPI despre participarea echipei României la EGOI:

https://www.facebook.com/permalink.php?story_fbid=pfbid033n1PPEfVcdASWtC4ZKtx6FMDqDFbcUJUtFFhdnTBYPVmVvwWCfhJk981FuFeZRtQl&id=100063938854638
