### ISSUE TITLE
Elemente de geometrie

### ISSUE THREAD

**Issue by DanaLica** [asociatia-sepi/documente-publice#39]

**Comment by EmCerchez** [comment]
Si Paul Diac lucreaza pentru geometrie

**Comment by pauldiac** [comment]
Am discutat cu @mariusnicoli si ne-am coordonat, probabil voi continua cu alta tema, e ok pentru mine ca nu am începusem nimic încă (din fericire/păcate).

**Comment by mariusnicoli** [comment]
Articolul cu elemente de geometrie:
https://docs.google.com/document/d/1B5DV7XXzCDx4Ei1Cojhv76w1ZwYlHZ8awCXi6gweFSk/edit?usp=sharing
